import { useMemo, useState } from 'react';
import AdminIcon from './AdminIcon';
import { ConfirmDialog, FilterSelect, Modal, StatusPill, Toast } from './AdminUI';
import { getAllTournaments } from '../data/dashboardSelectors';
import { cancelMatch, createMatch, formatMatchDate, getMatches, saveMatchResult, updateMatch, MATCH_ROUNDS } from '../data/matchStore';

const emptyForm = { tournamentId: '', round: 'League', teamA: '', teamB: '', date: '', time: '', venue: '' };
const emptyResult = { teamAScore: '', teamBScore: '', winner: '' };

export default function MatchesPage({ tournamentId = null }) {
  const [refresh, setRefresh] = useState(0); const [form, setForm] = useState({ ...emptyForm, tournamentId: tournamentId || '' }); const [isCreating, setIsCreating] = useState(false);
  const [editing, setEditing] = useState(null); const [resultMatch, setResultMatch] = useState(null); const [result, setResult] = useState(emptyResult); const [confirm, setConfirm] = useState(null); const [toast, setToast] = useState(null);
  const tournaments = useMemo(() => getAllTournaments(), [refresh]); const matches = useMemo(() => getMatches(tournamentId), [refresh, tournamentId]);
  const selectedTournament = tournaments.find((item) => item.id === (form.tournamentId || tournamentId)); const teams = selectedTournament?.teams || [];
  const change = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  const reset = () => { setEditing(null); setIsCreating(false); setForm({ ...emptyForm, tournamentId: tournamentId || '' }); };
  const submit = (event) => { event.preventDefault(); const response = editing ? updateMatch(editing.id, form) : createMatch(form); if (!response.ok) return setToast({ tone: 'danger', title: 'Match not saved', text: response.error }); reset(); setRefresh((value) => value + 1); setToast({ title: editing ? 'Match updated' : 'Match scheduled', text: 'The fixture is now available across the platform.' }); };
  const submitResult = (event) => { event.preventDefault(); const response = saveMatchResult(resultMatch.id, { teamA: resultMatch.teamA, teamB: resultMatch.teamB, ...result }); if (!response.ok) return setToast({ tone: 'danger', title: 'Result not saved', text: response.error }); setResultMatch(null); setRefresh((value) => value + 1); setToast({ title: 'Result saved', text: 'The bracket and public tournament page are updated.' }); };
  return <div className="admin-list-page">
    <div className="admin-dash-head"><div><span className="section-kicker">MATCHES & RESULTS</span><h2>{tournamentId ? `${selectedTournament?.name || 'Tournament'} fixtures` : 'Match management'}</h2><p>Schedule, reschedule and publish results for every fixture.</p></div><button type="button" className="btn btn-primary admin-action-btn" onClick={() => { reset(); setIsCreating(true); }}><AdminIcon name="plus" size={16} /> Create Match</button></div>
    <div className="admin-toolbar"><span className="admin-cell-muted">{matches.length} fixtures</span></div>
    {matches.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Round</th><th>Team A</th><th>Team B</th><th>Date</th><th>Time</th><th>Venue</th><th>Status</th><th>Actions</th></tr></thead><tbody>{matches.map((match) => <tr key={match.id}><td data-label="Round">{match.round}</td><td data-label="Team A"><strong>{match.teamA || 'TBD'}</strong></td><td data-label="Team B"><strong>{match.teamB || 'TBD'}</strong></td><td data-label="Date">{formatMatchDate(match.date)}</td><td data-label="Time">{match.time || '—'}</td><td data-label="Venue">{match.venue || '—'}</td><td data-label="Status"><StatusPill status={match.status} /></td><td data-label="Actions" className="admin-row-actions"><button type="button" className="admin-link-btn" onClick={() => { setEditing(match); setForm({ tournamentId: match.tournamentId, round: match.round, teamA: match.teamA, teamB: match.teamB, date: match.date, time: match.time, venue: match.venue }); }}>Edit</button><button type="button" className="admin-link-btn" onClick={() => { setEditing(match); setForm({ tournamentId: match.tournamentId, round: match.round, teamA: match.teamA, teamB: match.teamB, date: match.date, time: match.time, venue: match.venue }); }}>Reschedule</button>{match.status !== 'cancelled' && <button type="button" className="admin-link-btn danger" onClick={() => setConfirm(match)}>Cancel</button>}{match.status !== 'cancelled' && <button type="button" className="admin-link-btn" onClick={() => { setResultMatch(match); setResult(match.result ? { teamAScore: match.result.teamAScore || '', teamBScore: match.result.teamBScore || '', winner: match.result.winner || '' } : emptyResult); }}>Enter Result</button>}</td></tr>)}</tbody></table></div> : <div className="admin-empty"><strong>No matches scheduled</strong><p>Create the first fixture for this tournament.</p><button type="button" className="btn btn-primary" onClick={() => setIsCreating(true)}>Create Match</button></div>}
    <Modal open={Boolean(isCreating || editing)} title={editing ? 'Edit match' : 'Create match'} onClose={reset} size="lg" footer={<><button type="button" className="btn btn-secondary" onClick={reset}>Close</button><button type="submit" form="match-form" className="btn btn-primary">Save match</button></>}><form id="match-form" className="admin-form-grid" onSubmit={submit}><label className="form-field"><span>Tournament</span><select value={form.tournamentId} onChange={(event) => change('tournamentId', event.target.value)} required><option value="">Select tournament</option>{tournaments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="form-field"><span>Round</span><select value={form.round} onChange={(event) => change('round', event.target.value)}>{MATCH_ROUNDS.map((round) => <option key={round}>{round}</option>)}</select></label><label className="form-field"><span>Team A</span><select value={form.teamA} onChange={(event) => change('teamA', event.target.value)} required><option value="">Select team</option>{teams.map((team) => <option key={team.name}>{team.name}</option>)}</select></label><label className="form-field"><span>Team B</span><select value={form.teamB} onChange={(event) => change('teamB', event.target.value)} required><option value="">Select team</option>{teams.map((team) => <option key={team.name}>{team.name}</option>)}</select></label><label className="form-field"><span>Date</span><input type="date" value={form.date} onChange={(event) => change('date', event.target.value)} required /></label><label className="form-field"><span>Time</span><input type="time" value={form.time} onChange={(event) => change('time', event.target.value)} required /></label><label className="form-field"><span>Venue</span><input value={form.venue} onChange={(event) => change('venue', event.target.value)} /></label></form></Modal>
    <Modal open={Boolean(resultMatch)} title={`Enter result: ${resultMatch?.teamA} vs ${resultMatch?.teamB}`} onClose={() => setResultMatch(null)} footer={<><button type="button" className="btn btn-secondary" onClick={() => setResultMatch(null)}>Close</button><button type="submit" form="result-form" className="btn btn-primary">Save result</button></>}><form id="result-form" className="admin-form-grid" onSubmit={submitResult}><label className="form-field"><span>{resultMatch?.teamA} score</span><input value={result.teamAScore} onChange={(event) => setResult({ ...result, teamAScore: event.target.value })} placeholder="120/8, 2, or 11-7" required /></label><label className="form-field"><span>{resultMatch?.teamB} score</span><input value={result.teamBScore} onChange={(event) => setResult({ ...result, teamBScore: event.target.value })} placeholder="105/10, 1, or 11-9" required /></label><label className="form-field"><span>Winner</span><select value={result.winner} onChange={(event) => setResult({ ...result, winner: event.target.value })} required><option value="">Select winner</option><option value={resultMatch?.teamA}>{resultMatch?.teamA}</option><option value={resultMatch?.teamB}>{resultMatch?.teamB}</option></select></label></form></Modal>
    <ConfirmDialog open={Boolean(confirm)} title="Cancel match?" message={confirm ? `${confirm.teamA} vs ${confirm.teamB} will be marked cancelled.` : ''} confirmLabel="Cancel match" onCancel={() => setConfirm(null)} onConfirm={() => { cancelMatch(confirm.id); setConfirm(null); setRefresh((value) => value + 1); setToast({ tone: 'warn', title: 'Match cancelled' }); }} />
    <Toast toast={toast} onDismiss={() => setToast(null)} />
  </div>;
}