import { useState } from 'react';
import AdminIcon from './AdminIcon';
import { Toast } from './AdminUI';
import { changeAdminPassword, getAdminSettings, updateAdminSettings } from '../data/adminSettings';

const navigate = (href) => { window.location.href = href; };

export default function SettingsPage({ admin, logout }) {
  const initial = getAdminSettings();
  const [profile, setProfile] = useState({ name: initial.admin.name || admin?.name || '', email: initial.admin.email || admin?.email || '', phone: initial.admin.phone || '', profileImage: initial.admin.profileImage || '' });
  const [platform, setPlatform] = useState({ platformName: initial.platform.platformName || '', contactEmail: initial.platform.contactEmail || '', contactPhone: initial.platform.contactPhone || '', location: initial.platform.location || '' });
  const [tournament, setTournament] = useState({ registrationType: initial.tournament.registrationType || 'Team', defaultFormat: initial.tournament.defaultFormat || 'Knockout', defaultTeamCapacity: initial.tournament.defaultTeamCapacity || 8, defaultRegistrationOpen: initial.tournament.defaultRegistrationOpen !== false });
  const [password, setPassword] = useState({ current: '', next: '', confirm: '' });
  const [toast, setToast] = useState(null);
  const setField = (setter, field) => (event) => setter((value) => ({ ...value, [field]: event.target.type === 'checkbox' ? event.target.checked : event.target.value }));
  const save = (event) => { event.preventDefault(); const result = updateAdminSettings({ profile, platform, tournament }); setToast(result.ok ? { title: 'Settings saved', text: 'Changes persist in the shared demo state.' } : { tone: 'danger', title: 'Could not save', text: result.error }); };
  const updatePassword = (event) => { event.preventDefault(); if (password.next !== password.confirm) return setToast({ tone: 'danger', title: 'Passwords do not match' }); const result = changeAdminPassword(password.current, password.next); setToast(result.ok ? { title: 'Password changed' } : { tone: 'danger', title: 'Could not change password', text: result.error }); if (result.ok) setPassword({ current: '', next: '', confirm: '' }); };
  return <div className="admin-list-page settings-page"><div className="admin-dash-head"><div><span className="section-kicker">SETTINGS</span><h2>Platform settings</h2><p>Manage administrator access and the defaults used across the platform.</p></div><button type="button" className="btn btn-primary admin-action-btn" onClick={save}><AdminIcon name="check" size={16} /> Save settings</button></div>
    <form onSubmit={save} className="settings-grid"><section className="admin-panel settings-section"><div className="admin-panel-head"><div><span className="section-kicker">ADMIN PROFILE</span><h3>Administrator profile</h3></div></div><div className="admin-form-grid"><Field label="Name" value={profile.name} onChange={setField(setProfile, 'name')} required /><Field label="Email" type="email" value={profile.email} onChange={setField(setProfile, 'email')} required /><Field label="Phone" value={profile.phone} onChange={setField(setProfile, 'phone')} /><Field label="Profile Image" value={profile.profileImage} onChange={setField(setProfile, 'profileImage')} placeholder="Image URL" /></div></section>
      <section className="admin-panel settings-section"><div className="admin-panel-head"><div><span className="section-kicker">PLATFORM SETTINGS</span><h3>Public platform identity</h3></div></div><div className="admin-form-grid"><Field label="Platform Name" value={platform.platformName} onChange={setField(setPlatform, 'platformName')} required /><Field label="Contact Email" type="email" value={platform.contactEmail} onChange={setField(setPlatform, 'contactEmail')} /><Field label="Contact Phone" value={platform.contactPhone} onChange={setField(setPlatform, 'contactPhone')} /><Field label="Location" value={platform.location} onChange={setField(setPlatform, 'location')} /></div></section>
      <section className="admin-panel settings-section"><div className="admin-panel-head"><div><span className="section-kicker">TOURNAMENT SETTINGS</span><h3>Default tournament options</h3></div></div><div className="admin-form-grid"><label className="form-field"><span>Default registration settings</span><select value={tournament.registrationType} onChange={setField(setTournament, 'registrationType')}><option>Team</option><option>Individual</option></select></label><Field label="Default format" value={tournament.defaultFormat} onChange={setField(setTournament, 'defaultFormat')} /><Field label="Default team capacity" type="number" value={tournament.defaultTeamCapacity} onChange={setField(setTournament, 'defaultTeamCapacity')} /><label className="settings-checkbox"><input type="checkbox" checked={tournament.defaultRegistrationOpen} onChange={setField(setTournament, 'defaultRegistrationOpen')} /> Open registration by default</label></div></section>
    </form>
    <section className="admin-panel settings-section"><div className="admin-panel-head"><div><span className="section-kicker">SECURITY</span><h3>Access and security</h3></div></div><form className="admin-form-grid" onSubmit={updatePassword}><Field label="Current password" type="password" value={password.current} onChange={setField(setPassword, 'current')} required /><Field label="New password" type="password" value={password.next} onChange={setField(setPassword, 'next')} required /><Field label="Confirm new password" type="password" value={password.confirm} onChange={setField(setPassword, 'confirm')} required /><div className="settings-actions"><button type="submit" className="btn btn-secondary">Change password</button><button type="button" className="btn admin-btn-danger" onClick={() => { logout(); navigate('/admin/login'); }}>Logout</button></div></form></section>
    <Toast toast={toast} onDismiss={() => setToast(null)} />
  </div>;
}

function Field({ label, type = 'text', value, onChange, placeholder = '', required = false }) { return <label className="form-field"><span>{label}</span><input type={type} value={value} onChange={onChange} placeholder={placeholder} required={required} /></label>; }