import { useMemo, useState } from 'react';
import {
  createId,
  getAllTurfs,
  getBookings,
  getDemoState,
  saveBookings,
  saveDemoState,
} from './data/demoStore';
import { ACTIVITY_TYPES, recordActivity } from './data/activityStore';
import { route } from './config/routes';
const sections = ['Overview', 'My Turf', 'Bookings', 'Players', 'Player Requests', 'Teams', 'Availability'];
const formatDate = (value) => value ? new Date(`${value}T00:00:00`).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : 'Not selected';
const fullName = (player) => `${player?.firstName || ''} ${player?.surname || ''}`.trim() || 'Player';
const normalizeTurf = (turf = {}) => ({
  ...turf,
  name: turf.name || turf.turfName,
  sports: turf.sports?.length ? turf.sports : (turf.games || ['Cricket']),
  image: turf.image || turf.images?.[0] || turf.primaryImage || '',
  area: turf.area || turf.turfAddress?.area || turf.location || 'Vadodara',
});

function OwnerDashboard({ state, session, refresh, logout }) {
  const allTurfs = getAllTurfs().map(normalizeTurf);
  const owner = state.owners.find((item) => item.id === session.userId);
  const ownerTurfs = allTurfs.filter((turf) => turf.ownerId === owner?.id || owner?.turfIds?.includes(turf.id));
  const [section, setSection] = useState('Overview');
  const [selectedTurfId, setSelectedTurfId] = useState(() => new URLSearchParams(window.location.search).get('turfId') || session.turfId || ownerTurfs[0]?.id);
  const turf = ownerTurfs.find((item) => item.id === selectedTurfId) || ownerTurfs[0];
  const [menuOpen, setMenuOpen] = useState(false);

  if (!owner || !turf) return <OwnerAccessMessage logout={logout} />;

  const chooseSection = (next) => {
    setSection(next);
    setMenuOpen(false);
  };

  return <div className="owner-dashboard dashboard-app">
    <header className="app-topbar dashboard-topbar owner-dashboard-bar"><button type="button" className="app-brand" onClick={() => window.location.href = route('/turf-owner/dashboard')}><span className="brand-mark">VS</span><span>TURF OWNER WORKSPACE</span></button><div className="dashboard-top-actions"><span className="topbar-user">{owner.name}</span><button type="button" className="mobile-dashboard-menu" onClick={() => setMenuOpen((value) => !value)} aria-label="Toggle owner navigation">☰</button><button type="button" className="text-button" onClick={logout}>Logout</button></div></header>
    <div className={`dashboard-frame owner-dashboard-frame ${menuOpen ? 'nav-open' : ''}`}>
      <aside className="dashboard-sidebar owner-sidebar"><div className="sidebar-profile"><span className="large-avatar">{owner.name.slice(0, 2).toUpperCase()}</span><strong>{owner.name}</strong><span>Turf owner</span></div><div className="owner-turf-switcher"><span>MANAGE TURF</span><select value={turf.id} onChange={(event) => setSelectedTurfId(event.target.value)}>{ownerTurfs.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><nav>{sections.map((item) => <button type="button" className={section === item ? 'active' : ''} onClick={() => chooseSection(item)} key={item}>{item}</button>)}</nav><button type="button" className="sidebar-logout" onClick={logout}>Logout</button></aside>
      <div className="dashboard-content"><main className="dashboard-main container"><div className="page-title-row"><div><span className="section-kicker">OWNER DASHBOARD / {turf.area}</span><h1>{section.toUpperCase()}.</h1><p>Manage {turf.name} through one connected workspace. Login email: {owner.email}</p></div><span className="owner-badge">{turf.registrationStatus || 'REGISTERED'}</span></div>{section === 'Overview' && <Overview state={state} owner={owner} turf={turf} onNavigate={chooseSection} />}{section === 'My Turf' && <MyTurf state={state} owner={owner} turf={turf} refresh={refresh} />}{section === 'Bookings' && <Bookings state={state} owner={owner} turf={turf} refresh={refresh} />}{section === 'Players' && <Players state={state} owner={owner} turf={turf} />}{section === 'Player Requests' && <PlayerRequests state={state} owner={owner} turf={turf} refresh={refresh} />}{section === 'Teams' && <Teams state={state} owner={owner} turf={turf} refresh={refresh} />}{section === 'Availability' && <Availability state={state} owner={owner} turf={turf} refresh={refresh} />}</main></div>
    </div>
  </div>;
}

function Overview({ state, owner, turf, onNavigate }) {
  const bookings = getBookings().filter((booking) => booking.ownerId === owner.id && booking.turfId === turf.id);
  const requests = state.requests.filter((request) => request.ownerId === owner.id && request.turfId === turf.id);
  const players = state.players.filter((player) => requests.some((request) => request.playerId === player.id && request.status === 'accepted'));
  const teams = (state.teams || []).filter((team) => team.ownerId === owner.id && team.turfId === turf.id);
  const cards = [['Players', players.length, 'Players'], ['Pending requests', requests.filter((item) => item.status === 'pending').length, 'Player Requests'], ['Teams', teams.length, 'Teams'], ['Pending bookings', bookings.filter((item) => item.bookingStatus === 'pending').length, 'Bookings'], ['Confirmed bookings', bookings.filter((item) => item.bookingStatus === 'Confirmed').length, 'Bookings'], ["Today's slots", bookings.filter((item) => item.bookingStatus === 'Confirmed' && item.bookingDate === new Date().toISOString().slice(0, 10)).length, 'Availability']];
  return <><section className="owner-overview-hero"><img src={turf.image} alt={turf.name} /><div><span className="section-kicker">YOUR TURF</span><h2>{turf.name}</h2><p>{turf.location || turf.area}, Vadodara · {(turf.sports || []).join(' · ')}</p><strong>{turf.openingHours || 'Opening hours not set'}</strong></div></section><section className="owner-stat-grid">{cards.map(([label, value, target]) => <button type="button" className="owner-stat-card" key={label} onClick={() => onNavigate(target)}><span>{label}</span><strong>{value}</strong><small>Open {target}</small></button>)}</section><section className="owner-overview-grid"><article className="dashboard-block owner-info-panel"><SectionHeading kicker="TURF SUMMARY" title="READY FOR THE NEXT GAME." /><div className="detail-lines"><DetailLine label="Location" value={`${turf.area}, Vadodara`} /><DetailLine label="Games" value={(turf.sports || []).join(' · ')} /><DetailLine label="Facilities" value={(turf.facilities || []).join(' · ') || 'Not listed'} /><DetailLine label="Status" value={turf.registrationStatus || 'Registered'} /></div></article><article className="dashboard-block owner-info-panel"><SectionHeading kicker="RECENT ACTIVITY" title="WHAT NEEDS YOUR ATTENTION." /><ActivityLine label="Booking requests" value={bookings.filter((item) => item.bookingStatus === 'pending').length} onClick={() => onNavigate('Bookings')} /><ActivityLine label="Player requests" value={requests.filter((item) => item.status === 'pending').length} onClick={() => onNavigate('Player Requests')} /><ActivityLine label="Unavailable slots" value={(state.availability || []).filter((item) => item.ownerId === owner.id && item.turfId === turf.id).length} onClick={() => onNavigate('Availability')} /></article></section></>;
}

function MyTurf({ state, owner, turf, refresh }) {
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState({ name: turf.name, description: turf.turfDescription || turf.description || '', location: turf.location || '', contact: turf.turfContactNumber || owner.mobile || '', instructions: turf.bookingInstructions || '', rules: turf.rules || '' });
  const save = () => { const next = getDemoState(); const target = next.registeredTurfs.find((item) => item.id === turf.id); if (target) { Object.assign(target, { turfName: form.name.trim(), turfDescription: form.description.trim(), location: form.location.trim(), turfContactNumber: form.contact.trim(), bookingInstructions: form.instructions.trim(), rules: form.rules.trim(), area: target.turfAddress?.area || form.location.trim() }); saveDemoState(next); refresh(); setEditing(false); } };
  return <section className="owner-detail-layout"><article className="owner-profile-card"><img src={turf.image} alt={turf.name} /><span className="section-kicker">REGISTERED TURF</span><h2>{turf.name}</h2><p>{turf.location || turf.area}, Vadodara</p><button type="button" className="btn btn-primary" onClick={() => setEditing((value) => !value)}>{editing ? 'Cancel Editing' : 'Edit Turf'}</button></article><article className="owner-details-panel"><SectionHeading kicker="TURF PROFILE" title="EVERY DETAIL IN ONE PLACE." />{editing ? <div className="owner-edit-grid"><OwnerField label="Turf Name" value={form.name} onChange={(value) => setForm({ ...form, name: value })} /><OwnerField label="Location" value={form.location} onChange={(value) => setForm({ ...form, location: value })} /><OwnerField label="Contact" value={form.contact} onChange={(value) => setForm({ ...form, contact: value })} /><OwnerField label="Description" value={form.description} onChange={(value) => setForm({ ...form, description: value })} /><OwnerField label="Booking Instructions" value={form.instructions} onChange={(value) => setForm({ ...form, instructions: value })} /><OwnerField label="Rules" value={form.rules} onChange={(value) => setForm({ ...form, rules: value })} /><button type="button" className="btn btn-primary" onClick={save}>Save Turf Changes</button></div> : <><DetailGroup title="Owner Information"><DetailLine label="Name" value={owner.name} /><DetailLine label="Mobile" value={owner.mobile || turf.ownerMobile} /><DetailLine label="Email" value={owner.email || turf.ownerEmail} /><DetailLine label="Address" value={turf.ownerAddress || 'Not provided'} /></DetailGroup><DetailGroup title="Turf Information"><DetailLine label="Description" value={turf.turfDescription || turf.description || 'Not provided'} /><DetailLine label="Type / size" value={`${turf.turfType || 'Turf'} · ${turf.turfSize || 'Not provided'}`} /><DetailLine label="Sports" value={(turf.sports || []).join(' · ')} /><DetailLine label="Facilities" value={(turf.facilities || []).join(' · ') || 'Not provided'} /><DetailLine label="Opening hours" value={turf.openingHours || 'Not provided'} /><DetailLine label="Turf address" value={formatAddress(turf.turfAddress)} /><DetailLine label="Contact" value={turf.turfContactNumber || 'Not provided'} /><DetailLine label="Instructions / rules" value={`${turf.bookingInstructions || 'None'} / ${turf.rules || 'None'}`} /></DetailGroup></>}</article></section>;
}

function Bookings({ state, owner, turf, refresh }) {
  const bookings = getBookings().filter((item) => item.ownerId === owner.id && item.turfId === turf.id);
  const respond = (bookingId, status) => { const next = getBookings(); const booking = next.find((item) => item.bookingId === bookingId && item.ownerId === owner.id && item.turfId === turf.id); if (!booking) return; booking.bookingStatus = status; booking.updatedAt = new Date().toISOString(); saveBookings(next); refresh(); };
  return <section className="dashboard-block"><SectionHeading kicker="BOOKING REQUESTS" title="REVIEW EVERY RESERVATION." />{bookings.length ? <div className="owner-record-list">{bookings.map((booking) => <article className="owner-record" key={booking.bookingId}><div><span className="section-kicker">{booking.bookingId}</span><h3>{booking.userName}</h3><p>{booking.mobile} · {booking.email}</p><p>{booking.game} · {formatDate(booking.bookingDate)} · {booking.fromTime} to {booking.toTime}</p><small>{booking.paymentMethod} · {booking.paymentStatus}</small></div><div className="owner-record-actions"><StatusPill status={booking.bookingStatus} />{booking.bookingStatus === 'pending' && <><button type="button" className="btn btn-primary" onClick={() => respond(booking.bookingId, 'Confirmed')}>Accept</button><button type="button" className="btn btn-secondary" onClick={() => respond(booking.bookingId, 'Rejected')}>Reject</button></>}</div></article>)}</div> : <EmptyState title="No booking requests yet" text="Bookings for this turf will appear here." />}</section>;
}

function PlayerRequests({ state, owner, turf, refresh }) {
  const requests = state.requests.filter((item) => item.ownerId === owner.id && item.turfId === turf.id);
  const respond = (id, status) => { const next = getDemoState(); const request = next.requests.find((item) => item.id === id && item.ownerId === owner.id && item.turfId === turf.id); if (!request) return; request.status = status; request.respondedAt = new Date().toISOString(); recordActivity({ state: next, type: status === 'accepted' ? ACTIVITY_TYPES.REGISTRATION_APPROVED : ACTIVITY_TYPES.REGISTRATION_REJECTED, actorRole: 'turf-owner', actorName: owner.name, message: `Registration ${status} for ${request.sportId || 'sport'}`, targetPath: '/admin/registrations', meta: { requestId: request.id } }); saveDemoState(next); refresh(); };
  return <section className="dashboard-block"><SectionHeading kicker="PLAYER REQUESTS" title="WHO WANTS TO PLAY HERE." />{requests.length ? <div className="owner-record-list">{requests.map((request) => { const player = state.players.find((item) => item.id === request.playerId); return <article className="owner-record" key={request.id}><div className="owner-player-record"><span className="large-avatar">{fullName(player).slice(0, 2).toUpperCase()}</span><div><h3>{fullName(player)}</h3><p>{player?.age} years · {request.sportId} · {player?.mobile}</p><p>{player?.email} · {player?.house}, {player?.street}, {player?.city}</p><small>Requested {formatDate(request.createdAt?.slice(0, 10))}</small></div></div><div className="owner-record-actions"><StatusPill status={request.status} />{request.status === 'pending' && <><button type="button" className="btn btn-primary" onClick={() => respond(request.id, 'accepted')}>Accept</button><button type="button" className="btn btn-secondary" onClick={() => respond(request.id, 'rejected')}>Reject</button></>}</div></article>; })}</div> : <EmptyState title="No player requests yet" text="Requests for this turf stay private to this owner." />}</section>;
}

function Players({ state, owner, turf }) {
  const acceptedIds = state.requests.filter((item) => item.ownerId === owner.id && item.turfId === turf.id && item.status === 'accepted').map((item) => item.playerId);
  const players = state.players.filter((player) => acceptedIds.includes(player.id));
  return <section className="dashboard-block"><SectionHeading kicker="YOUR PLAYERS" title="PLAYERS CONNECTED TO THIS TURF." />{players.length ? <div className="owner-record-list">{players.map((player) => <article className="owner-record" key={player.id}><div className="owner-player-record"><span className="large-avatar">{fullName(player).slice(0, 2).toUpperCase()}</span><div><h3>{fullName(player)}</h3><p>{player.sportId} · {player.mobile} · {player.email}</p></div></div><StatusPill status="accepted" /></article>)}</div> : <EmptyState title="No accepted players yet" text="Accepted player requests will appear here." />}</section>;
}

function Teams({ state, owner, turf, refresh }) {
  const [editing, setEditing] = useState(null);
  const [form, setForm] = useState({ name: '', sport: turf.sports[0] || 'Cricket', description: '', members: [] });
  const players = state.players.filter((player) => state.requests.some((request) => request.ownerId === owner.id && request.turfId === turf.id && request.playerId === player.id && request.status === 'accepted'));
  const teams = (state.teams || []).filter((team) => team.ownerId === owner.id && team.turfId === turf.id);
  const save = () => { if (!form.name.trim()) return; const next = getDemoState(); next.teams = next.teams || []; const record = { id: editing || createId('team'), ownerId: owner.id, turfId: turf.id, name: form.name.trim(), sport: form.sport, description: form.description.trim(), memberIds: form.members, updatedAt: new Date().toISOString() }; const index = next.teams.findIndex((team) => team.id === record.id); if (index >= 0) next.teams[index] = record; else next.teams.push(record); saveDemoState(next); setEditing(null); setForm({ name: '', sport: turf.sports[0] || 'Cricket', description: '', members: [] }); refresh(); };
  const edit = (team) => { setEditing(team.id); setForm({ name: team.name, sport: team.sport, description: team.description || '', members: team.memberIds || [] }); };
  const remove = (id) => { if (!window.confirm('Delete this team? Players will remain connected to the turf.')) return; const next = getDemoState(); next.teams = (next.teams || []).filter((team) => team.id !== id); saveDemoState(next); refresh(); };
  return <section className="dashboard-block"><div className="section-action-row"><SectionHeading kicker="TEAM MANAGEMENT" title="BUILD TEAMS FOR YOUR GAMES." /><button type="button" className="btn btn-primary" onClick={() => { setEditing(''); setForm({ name: '', sport: turf.sports[0] || 'Cricket', description: '', members: [] }); }}>Create Team</button></div>{editing !== null && <article className="owner-form-panel"><div className="owner-edit-grid"><OwnerField label="Team Name" value={form.name} onChange={(value) => setForm({ ...form, name: value })} /><label className="form-field"><span>Sport / Game</span><select value={form.sport} onChange={(event) => setForm({ ...form, sport: event.target.value })}>{turf.sports.map((sport) => <option key={sport}>{sport}</option>)}</select></label><OwnerField label="Description" value={form.description} onChange={(value) => setForm({ ...form, description: value })} /><label className="form-field member-picker"><span>Players</span><select multiple value={form.members} onChange={(event) => setForm({ ...form, members: [...event.target.selectedOptions].map((option) => option.value) })}>{players.map((player) => <option key={player.id} value={player.id}>{fullName(player)}</option>)}</select></label></div><button type="button" className="btn btn-primary" onClick={save}>Save Team</button></article>}{teams.length ? <div className="team-grid">{teams.map((team) => <article className="team-card" key={team.id}><span className="sport-chip">{team.sport}</span><h3>{team.name}</h3><p>{team.description || 'No description added.'}</p><small>{(team.memberIds || []).length} member(s)</small><div className="owner-record-actions"><button type="button" className="btn btn-secondary" onClick={() => edit(team)}>Edit</button><button type="button" className="btn btn-secondary" onClick={() => remove(team.id)}>Delete</button></div></article>)}</div> : <EmptyState title="No teams yet" text="Create a team for one of this turf's supported games." />}</section>;
}

function Availability({ state, owner, turf, refresh }) {
  const [form, setForm] = useState({ sport: turf.sports[0] || 'Cricket', date: '', fromTime: '', toTime: '', reason: '' });
  const slots = (state.availability || []).filter((item) => item.ownerId === owner.id && item.turfId === turf.id);
  const save = () => { if (!form.date || !form.fromTime || !form.toTime) return; const next = getDemoState(); next.availability = next.availability || []; next.availability.push({ id: createId('availability'), ownerId: owner.id, turfId: turf.id, ...form, createdAt: new Date().toISOString() }); saveDemoState(next); setForm({ ...form, date: '', fromTime: '', toTime: '', reason: '' }); refresh(); };
  const remove = (id) => { if (!window.confirm('Delete this unavailable slot?')) return; const next = getDemoState(); next.availability = (next.availability || []).filter((item) => item.id !== id); saveDemoState(next); refresh(); };
  return <section className="dashboard-block"><SectionHeading kicker="AVAILABILITY" title="PROTECT THE TIME SLOTS YOU CONTROL." /><article className="owner-form-panel"><div className="owner-edit-grid"><label className="form-field"><span>Game / Sport</span><select value={form.sport} onChange={(event) => setForm({ ...form, sport: event.target.value })}>{turf.sports.map((sport) => <option key={sport}>{sport}</option>)}</select></label><OwnerField label="Date" type="date" value={form.date} onChange={(value) => setForm({ ...form, date: value })} /><OwnerField label="From Time" type="time" value={form.fromTime} onChange={(value) => setForm({ ...form, fromTime: value })} /><OwnerField label="To Time" type="time" value={form.toTime} onChange={(value) => setForm({ ...form, toTime: value })} /><OwnerField label="Reason" value={form.reason} onChange={(value) => setForm({ ...form, reason: value })} /></div><button type="button" className="btn btn-primary" onClick={save}>Add Unavailable Slot</button></article>{slots.length ? <div className="owner-record-list">{slots.map((slot) => <article className="owner-record" key={slot.id}><div><h3>{slot.sport} · {formatDate(slot.date)}</h3><p>{slot.fromTime} to {slot.toTime}</p><small>{slot.reason || 'Owner blocked slot'}</small></div><button type="button" className="btn btn-secondary" onClick={() => remove(slot.id)}>Delete</button></article>)}</div> : <EmptyState title="No manual unavailable slots" text="Add sport-specific unavailable times above." />}</section>;
}

function OwnerAccessMessage({ logout }) { return <div className="player-app"><GlobalHeader /><main className="registration-main container"><div className="registration-heading"><span className="section-kicker">ACCOUNT ACCESS</span><h1>OWNER DASHBOARD UNAVAILABLE.</h1><p>Log in with a turf owner account to manage a venue.</p><button type="button" className="btn btn-primary" onClick={() => { logout(); }}>Go to Login</button></div></main></div>; }
function SectionHeading({ kicker, title }) { return <div className="dashboard-section-heading"><span className="section-kicker">{kicker}</span><h2>{title}</h2></div>; }
function DetailGroup({ title, children }) { return <section className="detail-group"><h3>{title}</h3>{children}</section>; }
function DetailLine({ label, value }) { return <div className="detail-line"><span>{label}</span><strong>{value || 'Not provided'}</strong></div>; }
function ActivityLine({ label, value, onClick }) { return <button type="button" className="activity-line" onClick={onClick}><span>{label}</span><strong>{value}</strong></button>; }
function OwnerField({ label, type = 'text', value, onChange }) { return <label className="form-field"><span>{label}</span><input type={type} value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function StatusPill({ status }) { return <span className={`status-pill status-${String(status).replaceAll(' ', '-')}`}>{status}</span>; }
function EmptyState({ title, text }) { return <div className="dashboard-empty"><strong>{title}</strong><span>{text}</span></div>; }
function formatAddress(address = {}) { return [address.house, address.street, address.area, address.city, address.state, address.pincode].filter(Boolean).join(', ') || 'Not provided'; }

export default OwnerDashboard;
